watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: [ "*" ]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 4
      left: 6
      bottom: 0
      right: 6
    widgets:
      left: [ "glazewm_tiling_direction", "glazewm_workspaces", "active_window" ]
      center: [ "clock", "apps" ]
      right: [ "cava", "media", "cpu", "memory", "volume", "battery", "disk", "wallpapers", "power_menu" ]
widgets:
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span></span>{count}"
        interval: 30
        exclude: []
      windows_update:
        enabled: true
        label: "<span></span>{count}"
        interval: 240
        exclude: []
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
      calendar:
        alignment: "center"
        offset_top: 6
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_if_offline: true
      populated_label: "{display_name}"
      empty_label: "{display_name}"
      active_populated_label: "{display_name}"
      active_empty_label: "{display_name}"
      hide_empty_workspaces: true
      enable_scroll_switching: true
      reverse_scroll_direction: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "󰓡"
      vertical_label: "󰓢"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 2
        offset: [ 0, 0 ]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      hide_decimal: true
      location: "Delhi India"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "󰖙"
        clearNight: "󰖙"
        cloudyDay: "󰖙"
        cloudyNight: "󰖙"
        rainyDay: "󰖙"
        rainyNight: "󰖙"
        snowyIcyDay: "󰖙"
        snowyIcyNight: "󰖙"
        blizzardDay: "󰖙"
        default: "󰖙"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
      - ""
      - ""
      - ""
      - ""
      - ""
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: [ "", "Shut Down" ]
        restart: [ "", "Restart" ]
        signout: [ "󰍃", "Sign out" ]
        hibernate: [ "", "Hibernate" ]
        sleep: [ "⏾", "Sleep" ]
        cancel: [ "", "Cancel" ]

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      update_interval: 5000
      time_remaining_natural: false
      hide_unsupported: false
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: ""
        icon_critical: ""
        icon_low: ""
        icon_medium: ""
        icon_high: ""
        icon_full: ""
      label_shadow:
        enabled: true
        color: "black"
        radius: 2
        offset: [ 0, 0 ]

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span></span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [ 0, 0 ]

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span></span> {info[percent][total]}"
      label_alt: "<span></span> {info[histograms][cpu_percent]}"
      update_interval: 2000
    cpu_thresholds:
      low: 25
      medium: 50
      high: 90
    histogram_icons:
    - "▁"
    - "▁"
    - "▂"
    - "▃"
    - "▄"
    - "▅"
    - "▆"
    - "▇"
    - "█"
    histogram_num_columns: 8
    callbacks:
      on_right: "exec cmd /c Taskmgr"
    label_shadow:
      enabled: true
      color: "black"
      radius: 5
      offset: [ 0, 0 ]

  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      gradient: 1
      reverse: 0
      foreground: "#89b4fa"
      gradient_color_1: "#74c7ec"
      gradient_color_2: "#89b4fa"
      gradient_color_3: "#cba6f7"
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      hide_empty: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 40
        label_alt: 80
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 60
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      thumbnail_edge_fade: true
      icons:
        prev_track: "󰒮"
        next_track: "󰒭"
        play: "󰐊"
        pause: "󰏤"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 80
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [ 5, 5 ]
      scrolling_label:
        enabled: true
        update_interval_ms: 100
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span></span>"
      label_alt: "<span></span>"
      group_label:
        volume_labels: [ "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" ]
        show_label_name: false
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#fffffff"
        alignment: "center"
        offset_top: 0
      callbacks:
        on_left: "toggle_group"

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
      - { icon: "", launch: "notification_center" }
      - { icon: "", launch: "cmd /c Taskmgr" }
      - { icon: "", launch: "wt" }
      - { icon: "", launch: "C:\\Users\\amanm\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe" }
      - { icon: "󰈹", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
      - { icon: "󰨞", launch: "C:\\Users\\amanm\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" }

  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>󰸉</span>"
      image_path: "C:\\Users\\amanm\\dots\\Wallpaper"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true
